### ISSUE TITLE
[HW] Vignesh Kumar

### ISSUE THREAD

**Issue by mviku** [datastaxdevs/workshop-introduction-to-nosql#409]
**Name:** Vignesh Kumar
**Email:** mvigneshkumar19@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/vigneshkumar-muthuvijayan/

Attach the homework screenshots below:
-----------------------------------------

Step 4 - Key Value datastore steps(both before and after update)
![Step4-Final](https://user-images.githubusercontent.com/12881333/127689620-3fe26d16-10ef-4d97-aa32-809734e6efc2.PNG)

Try it out scenario
![Try-it-out-completion](https://user-images.githubusercontent.com/12881333/127690690-3b8956be-d3e5-4519-a93e-95d242e54646.PNG)

Step 5 - Graph database
For some reasons the datastax studio docker container does not start for me. I updated the RAM to even 10Gb, still it fails with a timeout exception of 20 seconds. The ReadMe says to wait 30s, but for me the container startup fails roughly in ~20 seconds. 
```
Starting ==== Jul 30, 2021 5:22:16 PM org.apache.catalina.core.StandardContext listenerStart
studio_1  | SEVERE: Exception sending context initialized event to listener instance of class [org.springframework.web.context.ContextLoaderListener]
studio_1  | java.lang.RuntimeException: java.util.concurrent.TimeoutException: Futures timed out after [20 seconds]
studio_1  |     at com.datastax.studio.aggregates.integration.akka.AkkaUtil.ask(AkkaUtil.java:94)
studio_1  |     at com.datastax.studio.aggregates.integration.akka.AkkaUtil.ask(AkkaUtil.java:52)
studio_1  |     at com.datastax.studio.aggregates.integration.akka.AggregateActorProxy.invoke(AggregateActorProxy.java:35)
studio_1  |     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
studio_1  |     at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
studio_1  |     at com.datastax.studio.settings.aggregate.SettingsAggregate$$EnhancerBySpringCGLIB$$314972ca.getInstanceSetting(<generated>)
studio_1  |     at com.datastax.studio.analytics.StudioAnalytics.isCloudInstance(StudioAnalytics.java:176)
studio_1  |     at com.datastax.studio.analytics.StudioAnalytics.init(StudioAnalytics.java:191)
studio_1  |     at com.datastax.studio.analytics.StudioAnalytics.onApplicationEvent(StudioAnalytics.java:169)
studio_1  |     at com.datastax.studio.analytics.StudioAnalytics.onApplicationEvent(StudioAnalytics.java:42)
studio_1  |     at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
studio_1  |     at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
studio_1  |     at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
studio_1  |     at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404)
studio_1  |     at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:358)
studio_1  |     at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:900)
studio_1  |     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554)
studio_1  |     at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:409)
studio_1  |     at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:291)
studio_1  |     at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
studio_1  |     at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
studio_1  |     at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
studio_1  |     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
studio_1  |     at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
studio_1  |     at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
studio_1  |     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
studio_1  |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
studio_1  |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
studio_1  |     at java.lang.Thread.run(Thread.java:748)
studio_1  | Caused by: java.util.concurrent.TimeoutException: Futures timed out after [20 seconds]
studio_1  |     at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
studio_1  |     at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
studio_1  |     at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
studio_1  |     at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
studio_1  |     at scala.concurrent.Await$.result(package.scala:190)
studio_1  |     at scala.concurrent.Await.result(package.scala)
studio_1  |     at com.datastax.studio.aggregates.integration.akka.AkkaUtil.ask(AkkaUtil.java:66)
studio_1  |     ... 28 more
studio_1  |
studio_1  | Jul 30, 2021 5:22:16 PM org.apache.catalina.core.StandardContext startInternal
studio_1  | SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
Starting ===== Jul 30, 2021 5:22:16 PM org.apache.catalina.core.StandardContext startInternal
studio_1  | SEVERE: Context [/api] startup failed due to previous errors
Starting ====== Jul 30, 2021 5:22:16 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesJdbc
studio_1  | WARNING: The web application [api] registered the JDBC driver [com.simba.spark.jdbc41.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
studio_1  | Jul 30, 2021 5:22:16 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
studio_1  | WARNING: The web application [api] appears to have started a thread named [EMF Reference Cleaner] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
studio_1  |  java.lang.Object.wait(Native Method)
studio_1  |  java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
studio_1  |  java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
studio_1  |  org.eclipse.emf.common.util.CommonUtil$1ReferenceClearingQueuePollingThread.run(CommonUtil.java:70)
studio_1  | Jul 30, 2021 5:22:16 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
studio_1  | WARNING: The web application [api] appears to have started a thread named [com.google.inject.internal.util.$Finalizer] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
studio_1  |  java.lang.Object.wait(Native Method)
studio_1  |  java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
studio_1  |  java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
studio_1  |  com.google.inject.internal.util.$Finalizer.run(Finalizer.java:114)
studio_1  | Jul 30, 2021 5:22:16 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
studio_1  | WARNING: The web application [api] appears to have started a thread named [Timer-0] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
studio_1  |  java.lang.Object.wait(Native Method)
studio_1  |  java.lang.Object.wait(Object.java:502)
studio_1  |  java.util.TimerThread.mainLoop(Timer.java:526)
studio_1  |  java.util.TimerThread.run(Timer.java:505)
studio_1  | Jul 30, 2021 5:22:16 PM org.apache.catalina.loader.WebappClassLoaderBase checkThreadLocalMapForLeaks
studio_1  | SEVERE: The web application [api] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@7e70bb5e]) and a value of type [akka.dispatch.forkjoin.ForkJoinPool.Submitter] (value [akka.dispatch.forkjoin.ForkJoinPool$Submitter@58dd6aa]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

studio_1  | Studio 6.8.9-6d48b8d failed to start.  Please see the logs for more details
workshop-introduction-to-nosql_studio_1 exited with code 1
```

**Comment by SonicDMG** [comment]
Hrmmm, that's strange with the Docker container. What OS are you running from? I've used both MacOS and Windows without issue and it sounds like you increased the amount of RAM allocated to Docker. I wonder if one of the listeners is failing to start if there is a port collision or something maybe?

**Comment by mviku** [comment]
Thanks @HadesArchitect  & @SonicDMG.
Port collision is a possibility yes. I will try to do the exercise again when I have more time. Btw is there any documentation for the docker image from where I can find the set of exposed ports

**Comment by SonicDMG** [comment]
Yes, here you go -> https://docs.datastax.com/en/security/6.0/security/secFirewallPorts.html in particular ports for Cassandra, Studio, and Graph so definitel 9091, 9042, 8182 and potentially some of the others on that list.
